### ISSUE TITLE
Fix HTML output of compliance-checker

### ISSUE THREAD

**Issue by agstephens** [agstephens/compliance-checker-as-pf#1]
The IOOS compliance checker allows the user to specify multiple "tests" to run on a file.
Each "test" relates to a python class where each method (whose name begins with "check_") 
constitutes a check to be made on that file.

The output can be written to a number of formats using the argument `-f`:
 - no arguments - output to the terminal
 - `-f json -o output.json` - write to JSON file
 - `-f html -o output.html` - write to HTML file
 - `-f txt -o output.txt` - write to Text file
 
The HTML output view is very useful but it currently only writes the output of the last
test to the output file. Any other tests are ignored or overwritten.

The task is to get the HTML file to show _all_ tests that are run and their outputs.

Here is the task broken down in detail:

1. Fork the compliance-checker on GitHub to your local GitHub:

 https://github.com/ioos/compliance-checker
 
2. Clone your fork to a local sandbox, and install dependencies in a virtual environment:

```
git clone https://github.com/<USERID>/compliance-checker
cd compliance-checker/

virtualenv --system-site-packages venv
source venv/bin/activate

pip install -r requirements.txt
pip install -r test_requirements.txt
pip install .
```

3. Test it runs:

```
cchecker.py -test acdd --test cf compliance_checker/tests/data/bad_data_type.nc
```

This should show the results of both the "acdd" and "cf" tests on the `bad_data_type.nc` file.

4. Run the text output and HTML output versions of the command:

To get text output:

```
cchecker.py -o output.txt -f text --test acdd --test cf compliance_checker/tests/data/bad_data_type.nc
```

And the HTML output:

```
cchecker.py -o output.html -f html --test acdd --test cf compliance_checker/tests/data/bad_data_type.nc
```

Compare the outputs and verify that only the second ("cf") test is stored in the `output.html` file.

5. Investigate the code and fix:

Find out where the HTML output is written and modify the code to fix it so that it records results of 
all tests.

6. Add tests:

If necessary, add tests to the code base.

7. Push changes to GitHub:

Push changes to your GitHub.

8. Create Pull Request on IOOS repository:

Create a PR on the IOOS master repo.

**Comment by joesingo** [comment]
Pull request created here https://github.com/ioos/compliance-checker/pull/545

**Comment by joesingo** [comment]
Now been merged! https://github.com/ioos/compliance-checker/commit/ad498e4b0dbeaf89ad7e5e0ad87f0934489a4263
